//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetVersionInformation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SetVersionInformation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- Adding Missing Attribute: {0}.
        /// </summary>
        internal static string AssemblyInfoUpdater_OutputMissingAttributes_____Adding_Missing_Attribute___0_ {
            get {
                return ResourceManager.GetString("AssemblyInfoUpdater_OutputMissingAttributes_____Adding_Missing_Attribute___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found File: {0}.
        /// </summary>
        internal static string AssemblyInfoUpdater_ProcessAssemblyInfoFile_Found_File___0_ {
            get {
                return ResourceManager.GetString("AssemblyInfoUpdater_ProcessAssemblyInfoFile_Found_File___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type : {0}.
        /// </summary>
        internal static string ExceptionType {
            get {
                return ResourceManager.GetString("ExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Tag : {0}.
        /// </summary>
        internal static string FoundTag {
            get {
                return ResourceManager.GetString("FoundTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing files in {0}.
        /// </summary>
        internal static string ProcessingFilesIn {
            get {
                return ResourceManager.GetString("ProcessingFilesIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Number: {0}.{1}.{2}.{3}.
        /// </summary>
        internal static string Program_Main_Version_Number___0___1___2___3_ {
            get {
                return ResourceManager.GetString("Program_Main_Version_Number___0___1___2___3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace:.
        /// </summary>
        internal static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Exception : {0}.
        /// </summary>
        internal static string UnexpectedException {
            get {
                return ResourceManager.GetString("UnexpectedException", resourceCulture);
            }
        }
    }
}
